export const slides = [
  { src: "/gallery/MASTER-gallery-photos-IMG_3200.jpg", description: "xxx", title: "Image 1" },
  { src: "/gallery/MASTER-gallery-photos-IMG_3225.jpg", description: "xxx", title: "Image 2" },
  { src: "/gallery/MASTER-gallery-photos-IMG_3246.jpg", description: "xxx", title: "Image 3" },
  { src: "/gallery/MASTER-gallery-photos-IMG_3300.jpg", description: "xxx", title: "Image 4" },
  { src: "/gallery/MASTER-gallery-photos-IMG_3335.jpg", description: "xxx", title: "Image 5" },
  { src: "/gallery/MASTER-gallery-photos-IMG_3384.jpg", description: "xxx", title: "Image 6" },
  { src: "/gallery/MASTER-gallery-photos-IMG_3471.jpg", description: "xxx", title: "Image 7" },
  { src: "/gallery/MASTER-gallery-photos-IMG_3484.jpg", description: "xxx", title: "Image 8" },
  { src: "/gallery/MASTER-gallery-photos-IMG_3508.jpg", description: "xxx", title: "Image 9" },
  { src: "/gallery/MASTER-gallery-photos-IMG_3611.jpg", description: "xxx", title: "Image 10" },
  { src: "/gallery/MASTER-gallery-photos-IMG_3660.jpg", description: "xxx", title: "Image 11" },
  { src: "/gallery/MASTER-gallery-photos-IMG_3685.jpg", description: "xxx", title: "Image 12" },
  { src: "/gallery/MASTER-gallery-photos-IMG_3770.jpg", description: "xxx", title: "Image 13" },
  { src: "/gallery/MASTER-gallery-photos-IMG_3967.jpg", description: "xxx", title: "Image 14" },
  { src: "/gallery/MASTER-gallery-photos-IMG_4014.jpg", description: "xxx", title: "Image 15" },
  { src: "/gallery/MASTER-gallery-photos-IMG_4024.jpg", description: "xxx", title: "Image 16" },
  { src: "/gallery/MASTER-gallery-photos-IMG_4224.jpg", description: "xxx", title: "Image 17" },
  // { src: "/gallery/MASTER-gallery-photos-IMG_4264.jpg", description: "xxx", title: "Image 18" },
  { src: "/gallery/MASTER-gallery-photos-IMG_4304.jpg", description: "xxx", title: "Image 19" },
  { src: "/gallery/MASTER-gallery-photos-IMG_4312.jpg", description: "xxx", title: "Image 20" },
  { src: "/gallery/MASTER-gallery-photos-IMG_4336.jpg", description: "xxx", title: "Image 21" },
  { src: "/gallery/MASTER-gallery-photos-IMG_4395.jpg", description: "xxx", title: "Image 22" },
  //April 2025
  { src: "/gallery/april/IMG_4524.jpg", description: "xxx", title: "Image 23" },
  { src: "/gallery/april/IMG_4622.jpg", description: "xxx", title: "Image 24" },
  { src: "/gallery/april/IMG_4664.jpg", description: "xxx", title: "Image 25" },
  { src: "/gallery/april/IMG_4726.jpg", description: "xxx", title: "Image 26" },
  { src: "/gallery/april/IMG_4731.jpg", description: "xxx", title: "Image 27" },
  { src: "/gallery/april/IMG_4755.jpg", description: "xxx", title: "Image 28" },
  { src: "/gallery/april/IMG_4757.jpg", description: "xxx", title: "Image 29" },
  { src: "/gallery/april/IMG_4879.jpg", description: "xxx", title: "Image 30" },
  { src: "/gallery/april/IMG_4917.jpg", description: "xxx", title: "Image 31" },
  { src: "/gallery/april/IMG_4991.jpg", description: "xxx", title: "Image 32" },
  { src: "/gallery/april/IMG_5017.jpg", description: "xxx", title: "Image 33" },
  { src: "/gallery/april/IMG_5179.jpg", description: "xxx", title: "Image 34" },
  { src: "/gallery/april/IMG_5214.jpg", description: "xxx", title: "Image 35" },
  { src: "/gallery/april/IMG_5249.jpg", description: "xxx", title: "Image 36" },
  { src: "/gallery/april/IMG_4425.jpg", description: "xxx", title: "Image 37" },
  { src: "/gallery/april/IMG_4465.jpg", description: "xxx", title: "Image 38" },

  //May 2025
  { src: "/gallery/may/MASTER-gallery-photos-IMG_5392.jpg", description: "xxx", title: "Image 39" },
  { src: "/gallery/may/MASTER-gallery-photos-IMG_5413.jpg", description: "xxx", title: "Image 40" },
  { src: "/gallery/may/MASTER-gallery-photos-IMG_5541.jpg", description: "xxx", title: "Image 41" },
  { src: "/gallery/may/MASTER-gallery-photos-IMG_5587.jpg", description: "xxx", title: "Image 42" },
];
